server:
  port: ${PORT:8080}

logging:
  level:
    org.atmosphere: warn

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:${DB_FILEPATH}
    username: sa
    password:
    driverClassName: org.h2.Driver

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - com.github.yusrproject
